SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FRAMERATE = 144

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_MOVE_SPEED = 200
SHOOT_COOLDOWN = 0.3

BULLET_SPEED = 350
BULLET_RADIUS = 5