SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FRAMERATE = 144

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_MOVE_SPEED = 200
SHOOT_COOLDOWN = 0.3
PLAYER_MAX_SHIELD = 3

BULLET_SPEED = 350
BULLET_RADIUS = 5

PICKUP_MAX_SPAWN = 60
PICKUP_MIN_SPAWN = 40
PICKUP_LIFETIME = 180
PICKUP_MAX = 3

PICKUP_SHIELD_MAX_RADIUS = 15
PICKUP_SHIELD_MIN_COEFFICIENT = 0.7
PICKUP_SHIELD_PULSE_HOLD = 0.4
